services:
  todoapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOTNET_VERSION: "8.0"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DB_NAME: ToDo
      DB_USER: todoapp
      DB_PASSWORD: verydangeruspassword
    expose:
      - "8080"
    volumes:
      - todoapp-db:/var/lib/mysql
    restart: unless-stopped

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/etc/caddy        # <-- mount folder, not file
    depends_on:
      - todoapp

volumes:
  todoapp-db:
