version: "3.9"

services:
  todoapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DB_NAME: ToDo
      DB_USER: todoapp
      DB_PASSWORD: verydangeruspassword
    expose:
      - "8080"
    volumes:
      - todoapp-db:/var/lib/mysql

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - todoapp

volumes:
  todoapp-db:
