# HTTP: used for Let's Encrypt + redirect to HTTPS
server {
    listen 80;
    server_name softwaresolutiongledisheygg.com www.softwaresolutiongledisheygg.com;

    # ACME HTTP-01 challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # everything else: redirect to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS: serves your app
server {
    listen 443 ssl;
    server_name softwaresolutiongledisheygg.com www.softwaresolutiongledisheygg.com;

    ssl_certificate     /etc/letsencrypt/live/softwaresolutiongledisheygg.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/softwaresolutiongledisheygg.com/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://todoapp:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        pro
